### ISSUE TITLE
Správanie hárku pri výpadku pripojenia na internet

### ISSUE THREAD

**Issue by 4zzz** [FMFI-UK-1-AIN-412/workbook#11]
Pri výpadku pripojenia na internet sa po úprave ktorá sa nepodarí commitnuť prestane zobrazovať hárok a nieje možné zopakovať pokus o uloženie alebo uložiť zmenu hárku lokálne.

**Comment by crnkjck** [comment]
Vyriešené offline režimom. Otestované.
