### ISSUE TITLE
Nová bunka by mala byť editovateľná a prázdna

### ISSUE THREAD

**Issue by crnkjck** [FMFI-UK-1-AIN-412/workbook#16]
Nová bunka by sa mala po vložení byť ihneď v editovateľnom stave. Textová by nemala mať žiadny obsah a editor by mal mať focus, je to len operácia navyše pre používateľa zmazať defaultový text.

Podobne aj vytvorenie nového hárku v prehliadači repozitára by malo hárok rovno otvoriť s focusnutou editovateľnou prvou bunkou bez zbytočného obsahu.

**Comment by 4zzz** [comment]
12ef6b374b4b36c5a061bd3548526b6b89923b8d

**Comment by crnkjck** [comment]
Dalo by sa spraviť, aby mal editor v bunke hneď aj focus?

**Comment by crnkjck** [comment]
`react-codemirror` ma prop `autofocus`: https://github.com/uiwjs/react-codemirror#props . Moze sa to ale spravat zle, ked je otvorenych viac editorov a ako to bude interagovat s problemom #25.

Tu je priklad pripojenia sa na focus a blur udalosti na nizsej urovni: https://stackblitz.com/edit/react-clyeej?file=src%2FApp.js To ale moze byt uz trocha prilis nepohodlne.

**Comment by crnkjck** [comment]
Fixed by #36, commits [c90a37b](https://github.com/FMFI-UK-1-AIN-412/workbook/pull/36/commits/c90a37b6bfd6e52eb5802dcaf38a2e93ab80fc66) and [4a150a4](https://github.com/FMFI-UK-1-AIN-412/workbook/pull/36/commits/4a150a492179526eeef01f74e0c8eefc461a980c).
