### ISSUE TITLE
Formátovanie komentárov

### ISSUE THREAD

**Issue by crnkjck** [FMFI-UK-1-AIN-412/workbook#17]
Text komentára by mal byť menší (boostrapová trieda _small_), orámovanie je zbytočné.

**Comment by 4zzz** [comment]
c541ee28bcd6160452d3ff0d220cd3b769f8dc93, 68bf483f810a64630f1a56782c03a96de01c9e4c

**Comment by crnkjck** [comment]
Vyriešené.
