### ISSUE TITLE
Ikona zámku

### ISSUE THREAD

**Issue by 4zzz** [FMFI-UK-1-AIN-412/workbook#18]
Ikona zámku, ktorá sa zobrazuje v hornej časti bunky by mohla byť súčasťou horného toolbaru, napríklad ako neaktívny secondary button. 

Pri zobrazení na telefóne sa prekrýva s toolbarom.

**Comment by crnkjck** [comment]
Indikator zamknutia by som ponechal v toolbare aj po odomknuti – len s ikonou odomknuteho zamku. Bez ohladu na stav by som pouzil by som radsej outlinove sekundarne tlacidlo (je transparentne, takze s vynutenym bielym pozadim: `variant="outline-secondary" className="bg-white"`).

Tlacidla ostatnych akcii by som dal tiez secondary (ale nie outline). 

Cela skupina tlacidiel tvoriaca toolbar by stacila mensia: `size="sm"`.

Na polohovanie toolbaru pouzivate zmes absolutneho polohovania zľava a transformacii. Lepsie by bolo vyhodit transformacie a ľavú polohu a pouzit:

```css
right: 1rem; /* polohujeme od praveho okraja */
top: -1rem; /* polohujeme horny okraj; -1rem je akurat pre male tlacidla, normalne by potrebovali trocha viac */
```

Este jeden detail: `.cellWrapper` by mal mat `position: relative;` v CSS, nie v atribute `style`.
