### ISSUE TITLE
Globalne definicie v KaTeXu

### ISSUE THREAD

**Issue by crnkjck** [FMFI-UK-1-AIN-412/workbook#5]

**Comment by 4zzz** [comment]
Skusal som option katexu `globalGroup`. Pri jeho pouziti sa katexu preda aj object `macros` a pri renderovani bunky sa do tohto objektu pridavaju nove definicie. Problem je v tom ze ked sa bunka znova prerenderuje a pokusi sa znova vytvorit definiciu skonci to s chybou lebo definicia s danym menom uz existuje. Neviem ci sa da lahko predist tomuto problemu.    

Mozno by bolo jednoduchsie mat v subore workbooku jeden string s globalnymi definiciami pre katex ktore by raz vytvorili objekt `macros` a ten by sa pouzil v kazdej textovej bunke. Bez pouzitia `globalGroup` by nebol problem s redefiniciou.

**Comment by crnkjck** [comment]
Druha moznost sa mi zda lepsia, ale vyzaduje nejaky interface na editovanie tychto globalnych definicii. Potencialne ale budeme potrebovat nastavenia kazdeho worksheetu, globalne definicie by mohli byt jedno z nich (ine by napr. mohla byt defaultova sada pravidiel pre tablovac, spolocne nastavenia parserov formul a podobne).

**Comment by 4zzz** [comment]
423e75d7c78dfbd55dee48e7271e46715a74237f

**Comment by crnkjck** [comment]
Pri pokuse o zadefinovanie makier som dostaval syntakticke chyby. Nevedel som vsak, o co ide. Nie je z KaTeXu k dispozicii podrobnejsia chybova hlaska?

**Comment by crnkjck** [comment]
Fixed by [423e75d](https://github.com/FMFI-UK-1-AIN-412/workbook/commit/423e75d7c78dfbd55dee48e7271e46715a74237f), #35, #36, commit [c9a3e61](https://github.com/FMFI-UK-1-AIN-412/workbook/pull/36/commits/c9a3e61f842e5139df001c5402cd9769cefbb795)
