### ISSUE TITLE
HTML v markdowne

### ISSUE THREAD

**Issue by crnkjck** [FMFI-UK-1-AIN-412/workbook#7]
Kedze harok podporuje iba velmi zakladny markdown, hodilo by sa povolit v bunkach aj HTML, aby sa dali robit napr. tabulky. Na nieco sa da pouzit aj KaTeX, ale kedze nefunguju globalne definicie, nie je to uplne pohodlne. Je to potencialne nebezpecne, no mozno existuje nejaka moznost zapnut v remark/rehype „safe HTML“.

**Comment by 4zzz** [comment]
Zda sa ze syntax markdownu sa da rozsirit na 'GitHub Flavored Markdown' rozsirenim zoznamu pluginov o remark-gfm v komponente ReactMarkdown

**Comment by crnkjck** [comment]
To by čiastočne problém vyriešilo. Ideálne by bolo, keby táto verzia GHFM podporovala aj vnorené „bezpečné“ HTML (tak ako skutočný GHFM tu na GitHube), kde fungujú elementy ako `var`, `sup`, dokonca aj niektoré atribúty.

**Comment by 4zzz** [comment]
58ba95d971b8821bd2babc482ab6a49a00b911ff

**Comment by crnkjck** [comment]
Otestované
